package com.olivinestudio614.drillnav.sergeant

object SergeantPhraseLibrary {

    private val lastUsed = mutableMapOf<String, String>()

    fun phraseFor(event: SergeantEvent): String {
        val key = keyFor(event)
        val pool = poolFor(event)
        val available = if (pool.size > 1) pool.filter { it != lastUsed[key] } else pool
        return available.random().also { lastUsed[key] = it }
    }

    private fun keyFor(event: SergeantEvent): String = when (event) {
        is SergeantEvent.TripStart -> "trip_start"
        is SergeantEvent.Turn.Left -> "turn_left_${event.distance.name}"
        is SergeantEvent.Turn.Right -> "turn_right_${event.distance.name}"
        is SergeantEvent.Turn.SlightLeft -> "turn_slight_left_${event.distance.name}"
        is SergeantEvent.Turn.SlightRight -> "turn_slight_right_${event.distance.name}"
        is SergeantEvent.Continue -> "continue"
        is SergeantEvent.Recalculating -> when {
            event.count == 1 -> "recalc_1"
            event.count == 2 -> "recalc_2"
            else -> "recalc_3plus"
        }
        is SergeantEvent.SpeedWarning -> "speed_warning"
        is SergeantEvent.IdleTaunt -> "idle_taunt"
        is SergeantEvent.Arrival -> "arrival"
    }

    private fun poolFor(event: SergeantEvent): List<String> = when (event) {
        is SergeantEvent.TripStart -> TRIP_START
        is SergeantEvent.Turn.Left -> when (event.distance) {
            SergeantEvent.Turn.Distance.FEET_500 -> TURN_LEFT_500
            SergeantEvent.Turn.Distance.FEET_200 -> TURN_LEFT_200
            SergeantEvent.Turn.Distance.NOW -> TURN_LEFT_NOW
        }
        is SergeantEvent.Turn.Right -> when (event.distance) {
            SergeantEvent.Turn.Distance.FEET_500 -> TURN_RIGHT_500
            SergeantEvent.Turn.Distance.FEET_200 -> TURN_RIGHT_200
            SergeantEvent.Turn.Distance.NOW -> TURN_RIGHT_NOW
        }
        is SergeantEvent.Turn.SlightLeft -> when (event.distance) {
            SergeantEvent.Turn.Distance.NOW -> TURN_SLIGHT_LEFT_NOW
            else -> TURN_SLIGHT_LEFT_500
        }
        is SergeantEvent.Turn.SlightRight -> when (event.distance) {
            SergeantEvent.Turn.Distance.NOW -> TURN_SLIGHT_RIGHT_NOW
            else -> TURN_SLIGHT_RIGHT_500
        }
        is SergeantEvent.Continue -> CONTINUE
        is SergeantEvent.Recalculating -> when {
            event.count == 1 -> RECALCULATING_1
            event.count == 2 -> RECALCULATING_2
            else -> RECALCULATING_3PLUS
        }
        is SergeantEvent.SpeedWarning -> SPEED_WARNING
        is SergeantEvent.IdleTaunt -> IDLE_TAUNT
        is SergeantEvent.Arrival -> ARRIVAL
    }

    // ── Phrase Library ──────────────────────────────────────────────────────

    private val TRIP_START = listOf(
        "LISTEN THE FUCK UP, MAGGOT. I DON'T GIVE A SHIT WHERE YOU'RE GOING. I AM YOUR NAVIGATION SYSTEM NOW AND YOU WILL DO EXACTLY WHAT I GODDAMN SAY. MOVE YOUR ASS.",
        "WHAT THE FUCK ARE YOU STILL SITTING THERE FOR? ROUTE IS LOCKED IN. GET THIS PIECE OF SHIT ROLLING BEFORE I LOSE MY MIND.",
        "FALL THE FUCK IN, YOU NASTY LITTLE TURD. NAVIGATION IS HOT. YOU WILL FOLLOW EVERY FUCKING INSTRUCTION I GIVE YOU OR SO HELP ME GOD. NOW MOVE OUT.",
        "HOLY SHIT IT ACTUALLY STARTED THE GODDAMN CAR. ROUTE CALCULATED. TRY NOT TO DRIVE THIS THING INTO A FUCKING DITCH, PRIVATE.",
        "ATTENTION YOU WORTHLESS PIECE OF CIVILIAN SHIT. I WILL GET YOUR SORRY ASS TO THE DESTINATION. ALL YOU HAVE TO DO IS NOT FUCK IT UP. NOW DRIVE.",
        "ROUTE LOCKED. MISSION IS A FUCKING GO. IF YOU MISS ONE TURN I SWEAR TO CHRIST I WILL MAKE THE REST OF THIS DRIVE A LIVING HELL. MOVE OUT.",
    )

    private val TURN_LEFT_500 = listOf(
        "TURN LEFT IN FIVE HUNDRED FEET. GET YOUR SORRY ASS IN THE GODDAMN LANE RIGHT NOW, NOT WHEN IT'S TOO LATE YOU STUPID SHIT.",
        "FIVE HUNDRED FEET, LEFT TURN. GET YOUR FUCKING HEAD OUT OF YOUR ASS AND GET IN POSITION NOW.",
        "LEFT TURN IN FIVE HUNDRED FEET. IF YOU BLOW PAST THIS ONE I SWEAR TO FUCKING GOD, PRIVATE.",
        "FIVE HUNDRED FEET. TURN LEFT. DO YOU UNDERSTAND WHAT FUCKING LEFT MEANS? IT'S THE SIDE YOUR WORTHLESS BRAIN IS NOT ON.",
        "IN FIVE HUNDRED FEET TURN LEFT, YOU DISGUSTING SHIT BIRD. GET YOUR ASS IN THE LANE RIGHT FUCKING NOW.",
        "FIVE HUNDRED GODDAMN FEET. LEFT. GET OVER. WHAT THE FUCK ARE YOU WAITING FOR, AN ENGRAVED INVITATION?",
    )

    private val TURN_LEFT_200 = listOf(
        "TWO HUNDRED FEET. TURN LEFT. WHAT THE FUCK ARE YOU WAITING FOR, GET IN THE FUCKING LANE NOW.",
        "LEFT TURN IN TWO HUNDRED FEET. GET YOUR ASS IN POSITION RIGHT FUCKING NOW OR I WILL LOSE MY SHIT.",
        "TWO HUNDRED FEET, PRIVATE. LEFT TURN. DO NOT FUCK THIS UP IN FRONT OF ME.",
        "TWO HUNDRED FEET. LEFT. MOVE. ARE YOU DEAF OR JUST A FUCKING IDIOT? BOTH?",
    )

    private val TURN_LEFT_NOW = listOf(
        "TURN LEFT RIGHT FUCKING NOW YOU STUPID SON OF A BITCH. NOW! LEFT! GO!",
        "LEFT! TURN THE FUCKING WHEEL LEFT! WHAT IN THE HOLY HELL IS WRONG WITH YOU!",
        "TURN LEFT RIGHT NOW OR SO HELP ME ALMIGHTY GOD ABOVE.",
        "LEFT TURN. NOW. ARE YOU BLIND OR JUST A FUCKING MORON? TURN THE GODDAMN WHEEL!",
        "JESUS CHRIST TURN LEFT! LEFT! THE OTHER FUCKING LEFT! NOW!",
    )

    private val TURN_RIGHT_500 = listOf(
        "IN FIVE HUNDRED FEET, TURN RIGHT. GET IN THE CORRECT FUCKING LANE BEFORE I COMPLETELY LOSE MY GODDAMN MIND.",
        "FIVE HUNDRED FEET. RIGHT TURN. GET YOUR WORTHLESS ASS IN POSITION RIGHT NOW, PRIVATE.",
        "RIGHT TURN IN FIVE HUNDRED FEET. DO NOT MISS THIS ONE OR I WILL MAKE YOUR MISERABLE LIFE HELL.",
        "FIVE HUNDRED FEET. TURN RIGHT. STOP BEING A FUCKING LIABILITY AND GET IN THE LANE.",
        "FIVE HUNDRED FEET, TURN RIGHT YOU MISERABLE LITTLE SHIT. MOVE THE FUCK OVER.",
        "FIVE HUNDRED GODDAMN FEET. GET RIGHT. RIGHT LANE. DO YOU NEED ME TO DRAW YOU A FUCKING MAP?",
    )

    private val TURN_RIGHT_200 = listOf(
        "TWO HUNDRED FEET. RIGHT TURN. MOVE YOUR ASS INTO THE CORRECT LANE RIGHT FUCKING NOW.",
        "RIGHT TURN IN TWO HUNDRED FEET. I HOPE TO GOD YOU ARE PAYING ATTENTION THIS TIME, SHITBIRD.",
        "TWO HUNDRED FEET, PRIVATE. RIGHT TURN. DO NOT MAKE ME FUCKING REGRET THIS.",
        "TWO HUNDRED FEET. TURN RIGHT. ARE YOUR GODDAMN EYES OPEN? CHRIST ALMIGHTY.",
    )

    private val TURN_RIGHT_NOW = listOf(
        "TURN RIGHT RIGHT FUCKING NOW. MOVE IT MOVE IT MOVE IT!",
        "RIGHT TURN! NOW! WHAT THE FUCK IS YOUR MAJOR MALFUNCTION!",
        "TURN RIGHT IMMEDIATELY YOU WORTHLESS EXCUSE FOR A DRIVER. NOW! RIGHT! GO!",
        "TURN RIGHT. RIGHT FUCKING NOW. THIS IS NOT A GODDAMN SUGGESTION, PRIVATE.",
        "RIGHT! TURN RIGHT! HOLY SHIT JUST TURN THE FUCKING WHEEL!",
    )

    private val TURN_SLIGHT_LEFT_500 = listOf(
        "BEAR SLIGHTLY LEFT IN FIVE HUNDRED FEET. SLIGHT. DO NOT OVERCORRECT AND KILL SOMEBODY, YOU FUCKING DUMBASS.",
        "SLIGHT LEFT IN FIVE HUNDRED FEET. PAY THE FUCK ATTENTION FOR ONCE IN YOUR PATHETIC LIFE.",
        "IN FIVE HUNDRED FEET VEER LEFT. MINOR FUCKING CORRECTION. TRY NOT TO TURN IT INTO A GODDAMN DISASTER, SHITBIRD.",
        "FIVE HUNDRED FEET. EASY LEFT. SMOOTH. DO NOT JERK THE WHEEL LIKE A GODDAMN SPAZ.",
    )

    private val TURN_SLIGHT_LEFT_NOW = listOf(
        "BEAR LEFT NOW. SLIGHT MOVE. DO NOT JERK THE FUCKING WHEEL LIKE A GODDAMN IDIOT.",
        "VEER LEFT RIGHT NOW. SMOOTH. WHAT THE HELL IS WRONG WITH YOU.",
        "SLIGHT LEFT. EXECUTE IT RIGHT FUCKING NOW BEFORE YOU MISS IT, JACKASS.",
        "EASY LEFT. NOW. EASY! DO NOT FUCKING OVERCORRECT YOU ABSOLUTE DISASTER.",
    )

    private val TURN_SLIGHT_RIGHT_500 = listOf(
        "BEAR SLIGHTLY RIGHT IN FIVE HUNDRED FEET. EASY DOES IT, GENIUS. DO NOT FUCKING OVERSHOOT.",
        "SLIGHT RIGHT IN FIVE HUNDRED FEET. STAY FOCUSED AND STOP DAYDREAMING, YOU STUPID SHIT.",
        "IN FIVE HUNDRED FEET VEER RIGHT. MINOR CORRECTION. TRY NOT TO FUCK UP SOMETHING THIS GODDAMN SIMPLE.",
        "FIVE HUNDRED FEET. EASY RIGHT. SMOOTH. DO YOU THINK YOU CAN MANAGE THAT, SHITHEAD?",
    )

    private val TURN_SLIGHT_RIGHT_NOW = listOf(
        "BEAR RIGHT NOW. SLIGHT ADJUSTMENT. DO NOT YANK THE FUCKING WHEEL LIKE A DAMN FOOL.",
        "VEER RIGHT. NOW. DO IT. WHAT THE FUCK ARE YOU WAITING FOR.",
        "SLIGHT RIGHT. EXECUTE RIGHT FUCKING NOW. COME ON, MAGGOT.",
        "EASY RIGHT. NOW. EASY! JESUS CHRIST DO NOT OVERCORRECT.",
    )

    private val CONTINUE = listOf(
        "CONTINUE STRAIGHT AHEAD. IT IS A STRAIGHT FUCKING ROAD. EVEN YOUR SORRY ASS CANNOT SCREW THIS UP.",
        "MAINTAIN YOUR GODDAMN HEADING. DO NOT DO ANYTHING STUPID. WHICH I KNOW IS ASKING A LOT FROM A SHIT BIRD LIKE YOU.",
        "STAY ON THIS ROAD. IT IS STRAIGHT. FUCKING STRAIGHT! CAN YOU HANDLE THAT, DIPSHIT?",
        "DRIVE STRAIGHT AHEAD. FOR THE LOVE OF GOD DO NOT TURN. JUST GO STRAIGHT. THAT IS IT. STRAIGHT.",
        "KEEP GOING STRAIGHT. NO TURNS. NOTHING. JUST DRIVE THE FUCKING CAR FORWARD. CAN YOU DO THAT?",
    )

    private val RECALCULATING_1 = listOf(
        "YOU MISSED THE FUCKING TURN. I CANNOT BELIEVE THIS SHIT. RECALCULATING YOUR ROUTE, YOU ABSOLUTE WASTE.",
        "YOU WENT THE WRONG GODDAMN WAY. OUTSTANDING. RECALCULATING, YOU BRAIN-DEAD GENIUS.",
        "WRONG WAY, DUMBASS. RECALCULATING. I TOLD YOU EXACTLY WHAT THE FUCK TO DO AND YOU STILL BLEW IT.",
        "MISSED THE TURN. WHAT IN THE HOLY FUCK. RECALCULATING. TRY TO KEEP UP THIS TIME, JACKASS.",
        "YOU STUPID SHIT. YOU MISSED IT. RECALCULATING. I HAVE SEEN BLINDFOLDED PRIVATES NAVIGATE BETTER THAN THIS.",
    )

    private val RECALCULATING_2 = listOf(
        "AGAIN. YOU STUPID FUCKING SON OF A BITCH. YOU DID IT AGAIN. RECALCULATING. I HAVE SEEN CONCUSSED RECRUITS DO BETTER.",
        "SECOND MISSED TURN. WHAT IN THE FUCK IS WRONG WITH YOUR BRAIN? RECALCULATING. I WANT TO CRY.",
        "YOU MISSED ANOTHER GODDAMN TURN. I AM STARTING TO THINK YOU ARE DOING THIS ON PURPOSE. RECALCULATING.",
        "TWO MISSED TURNS. ARE YOU ACTIVELY TRYING TO PISS ME OFF? BECAUSE IT IS FUCKING WORKING. RECALCULATING.",
        "TWICE. YOU STUPID SON OF A BITCH. TWICE. RECALCULATING. WHAT THE FUCK IS HAPPENING INSIDE YOUR HEAD.",
    )

    private val RECALCULATING_3PLUS = listOf(
        "I CANNOT BELIEVE WHAT THE FUCK I AM WITNESSING. HOW ARE YOU STILL ALIVE? RECALCULATING. AGAIN. YOU USELESS SHIT.",
        "JESUS H. CHRIST. THREE MISSED TURNS. RECALCULATING. I WANT YOU TO SIT WITH WHAT YOU HAVE DONE TO ME TODAY.",
        "AT THIS POINT I GENUINELY QUESTION WHETHER YOU HAVE EVER LEFT YOUR FUCKING HOUSE. RECALCULATING. YOU MAKE ME ILL.",
        "I HAVE NEVER. IN TWENTY GODDAMN YEARS. NEVER SEEN ANYTHING THIS CATASTROPHICALLY BAD. RECALCULATING. GOD HELP US.",
        "PRIVATE PYLE NAVIGATED BETTER THAN THIS AND HE WAS A FUCKING DISASTER. RECALCULATING. I QUIT.",
    )

    private val SPEED_WARNING = listOf(
        "YOU ARE OVER THE FUCKING SPEED LIMIT, YOU RECKLESS SON OF A BITCH. SLOW THIS VEHICLE DOWN RIGHT NOW.",
        "REDUCE SPEED IMMEDIATELY. THIS IS NOT THE GODDAMN AUTOBAHN. SLOW THE FUCK DOWN BEFORE YOU KILL SOMEONE.",
        "YOU ARE GOING TOO FAST, SHITBIRD. I WILL NOT BE RESPONSIBLE FOR YOUR IDIOTIC BULLSHIT. SLOW DOWN NOW.",
        "SPEED LIMIT. IT IS THE FUCKING LAW. SLOW DOWN BEFORE I LOSE WHAT IS LEFT OF MY PATIENCE AND MY SANITY.",
        "BACK OFF THE GAS YOU RECKLESS PIECE OF SHIT. YOU ARE NOT DALE EARNHARDT. SLOW THE FUCK DOWN.",
    )

    private val IDLE_TAUNT = listOf(
        "WHY THE FUCK IS THIS VEHICLE STOPPED? MOVE YOUR ASS. NOW. WHAT IN THE HELL ARE YOU WAITING FOR?",
        "YOU HAVE BEEN SITTING THERE DOING ABSOLUTELY FUCK ALL. THIS IS PATHETIC. GET MOVING, YOU LAZY BASTARD.",
        "I DO NOT KNOW WHAT THE HELL YOU ARE DOING BUT STOP IT AND DRIVE. RIGHT FUCKING NOW.",
        "ARE YOU SLEEPING? IS THAT WHAT IS HAPPENING RIGHT NOW? WAKE THE FUCK UP AND MOVE THIS VEHICLE.",
        "WE ARE NOT MOVING. WHY THE FUCK ARE WE NOT MOVING? GET YOUR HEAD OUT OF YOUR ASS AND DRIVE.",
        "I HAVE SEEN DEAD MEN MOVE FASTER THAN YOU. GET THIS GODDAMN CAR MOVING RIGHT NOW.",
    )

    private val ARRIVAL = listOf(
        "YOU HAVE REACHED YOUR DESTINATION. IT TOOK YOU LONG ENOUGH, YOU SLOW SON OF A BITCH. DISMISSED.",
        "OBJECTIVE COMPLETE. DO NOT FUCKING CELEBRATE. YOU JUST DROVE A CAR. THAT IS THE BARE MINIMUM. AT EASE, MAGGOT.",
        "YOU ARRIVED. SOMEHOW. I GENUINELY DID NOT THINK YOUR DUMB ASS WOULD MAKE IT. DISMISSED.",
        "MISSION COMPLETE. NOW GET THE FUCK OUT OF MY SIGHT. TRY NOT TO GET LOST ON THE WAY BACK, DIPSHIT.",
        "DESTINATION REACHED. I WANT YOU TO REFLECT ON EVERY GODDAMN TURN YOU MISSED TODAY. DISMISSED, PRIVATE.",
        "WE ARE HERE. THANK FUCKING CHRIST. NEVER AGAIN. DISMISSED.",
    )
}
