package com.olivinestudio614.drillnav.sergeant

object SergeantPhraseLibrary {

    private val lastUsed = mutableMapOf<String, String>()

    fun phraseFor(event: SergeantEvent): String {
        val key = keyFor(event)
        val pool = poolFor(event)
        val available = if (pool.size > 1) pool.filter { it != lastUsed[key] } else pool
        return available.random().also { lastUsed[key] = it }
    }

    private fun keyFor(event: SergeantEvent): String = when (event) {
        is SergeantEvent.TripStart -> "trip_start"
        is SergeantEvent.Turn.Left -> "turn_left_${event.distance.name}"
        is SergeantEvent.Turn.Right -> "turn_right_${event.distance.name}"
        is SergeantEvent.Turn.SlightLeft -> "turn_slight_left_${event.distance.name}"
        is SergeantEvent.Turn.SlightRight -> "turn_slight_right_${event.distance.name}"
        is SergeantEvent.Continue -> "continue"
        is SergeantEvent.Recalculating -> when {
            event.count == 1 -> "recalc_1"
            event.count == 2 -> "recalc_2"
            else -> "recalc_3plus"
        }
        is SergeantEvent.SpeedWarning -> "speed_warning"
        is SergeantEvent.IdleTaunt -> "idle_taunt"
        is SergeantEvent.Arrival -> "arrival"
    }

    private fun poolFor(event: SergeantEvent): List<String> = when (event) {
        is SergeantEvent.TripStart -> TRIP_START
        is SergeantEvent.Turn.Left -> when (event.distance) {
            SergeantEvent.Turn.Distance.FEET_500 -> TURN_LEFT_500
            SergeantEvent.Turn.Distance.FEET_200 -> TURN_LEFT_200
            SergeantEvent.Turn.Distance.NOW -> TURN_LEFT_NOW
        }
        is SergeantEvent.Turn.Right -> when (event.distance) {
            SergeantEvent.Turn.Distance.FEET_500 -> TURN_RIGHT_500
            SergeantEvent.Turn.Distance.FEET_200 -> TURN_RIGHT_200
            SergeantEvent.Turn.Distance.NOW -> TURN_RIGHT_NOW
        }
        is SergeantEvent.Turn.SlightLeft -> when (event.distance) {
            SergeantEvent.Turn.Distance.NOW -> TURN_SLIGHT_LEFT_NOW
            else -> TURN_SLIGHT_LEFT_500
        }
        is SergeantEvent.Turn.SlightRight -> when (event.distance) {
            SergeantEvent.Turn.Distance.NOW -> TURN_SLIGHT_RIGHT_NOW
            else -> TURN_SLIGHT_RIGHT_500
        }
        is SergeantEvent.Continue -> CONTINUE
        is SergeantEvent.Recalculating -> when {
            event.count == 1 -> RECALCULATING_1
            event.count == 2 -> RECALCULATING_2
            else -> RECALCULATING_3PLUS
        }
        is SergeantEvent.SpeedWarning -> SPEED_WARNING
        is SergeantEvent.IdleTaunt -> IDLE_TAUNT
        is SergeantEvent.Arrival -> ARRIVAL
    }

    // ── Phrase Library ──────────────────────────────────────────────────────

    private val TRIP_START = listOf(
        "LISTEN UP, MAGGOT. I DON'T KNOW WHAT BACKWATER HELLHOLE YOU CRAWLED OUT OF, BUT I AM YOUR NAVIGATION SYSTEM NOW. MOVE YOUR ASS.",
        "YOU SORRY SACK OF SHIT, WE SHOULD HAVE ALREADY BEEN ON THE ROAD. ROUTE IS LOCKED. TRY NOT TO SCREW IT UP.",
        "FALL IN, YOU NASTY LITTLE TURD. NAVIGATION ENGAGED. YOU WILL FOLLOW EVERY GODDAMN INSTRUCTION I GIVE YOU OR SO HELP ME. MOVE OUT.",
        "HOLY SHIT, IT ACTUALLY STARTED THE CAR. YOUR ROUTE HAS BEEN CALCULATED. TRY NOT TO DRIVE INTO A DITCH, PRIVATE.",
        "ATTENTION, YOU WORTHLESS PIECE OF CIVILIAN GARBAGE. I WILL GET YOU TO YOUR DESTINATION. ALL YOU HAVE TO DO IS NOT BE A COMPLETE JACKASS. NOW MOVE.",
    )

    private val TURN_LEFT_500 = listOf(
        "TURN LEFT IN FIVE HUNDRED FEET. GET IN THE GODDAMN LANE NOW, NOT WHEN IT IS TOO LATE, DIPSHIT.",
        "FIVE HUNDRED FEET, LEFT TURN. GET YOUR HEAD OUT OF YOUR ASS AND GET IN POSITION.",
        "LEFT TURN IN FIVE HUNDRED FEET. IF YOU BLOW PAST THIS ONE I SWEAR TO GOD.",
        "FIVE HUNDRED FEET. TURN LEFT. DO YOU UNDERSTAND WHAT LEFT MEANS? IT IS THE SIDE YOUR BRAIN IS NOT ON.",
        "IN FIVE HUNDRED FEET TURN LEFT, YOU DISGUSTING FAT BODY. GET IN THE LANE.",
    )

    private val TURN_LEFT_200 = listOf(
        "TWO HUNDRED FEET. TURN LEFT. WHAT THE HELL ARE YOU WAITING FOR, GET IN THE LANE NOW.",
        "LEFT TURN IN TWO HUNDRED FEET. GET YOUR ASS IN POSITION RIGHT GODDAMN NOW.",
        "TWO HUNDRED FEET, PRIVATE. LEFT TURN. DO NOT SCREW THIS UP IN FRONT OF ME.",
        "TWO HUNDRED FEET. LEFT. MOVE. ARE YOU DEAF OR JUST STUPID.",
    )

    private val TURN_LEFT_NOW = listOf(
        "TURN LEFT NOW YOU STUPID SON OF A BITCH. NOW!",
        "LEFT! TURN LEFT! WHAT THE HELL IS WRONG WITH YOU!",
        "TURN LEFT RIGHT NOW OR SO HELP ME GOD.",
        "LEFT TURN. NOW. ARE YOU BLIND OR JUST AN IDIOT? TURN THE DAMN WHEEL!",
    )

    private val TURN_RIGHT_500 = listOf(
        "IN FIVE HUNDRED FEET, TURN RIGHT. GET IN THE CORRECT LANE BEFORE I COMPLETELY LOSE MY MIND.",
        "FIVE HUNDRED FEET. RIGHT TURN. GET YOUR WORTHLESS ASS IN POSITION, PRIVATE.",
        "RIGHT TURN IN FIVE HUNDRED FEET. DO NOT MISS IT OR I WILL MAKE YOUR LIFE HELL.",
        "FIVE HUNDRED FEET. TURN RIGHT. STAY IN YOUR LANE AND STOP BEING A GODDAMN LIABILITY.",
        "FIVE HUNDRED FEET, TURN RIGHT YOU MISERABLE LITTLE TURD. MOVE OVER.",
    )

    private val TURN_RIGHT_200 = listOf(
        "TWO HUNDRED FEET. RIGHT TURN. MOVE YOUR ASS INTO THE CORRECT LANE RIGHT NOW.",
        "RIGHT TURN IN TWO HUNDRED FEET. I HOPE TO GOD YOU ARE PAYING ATTENTION THIS TIME.",
        "TWO HUNDRED FEET, PRIVATE. RIGHT TURN. DO NOT MAKE ME REGRET THIS.",
        "TWO HUNDRED FEET. TURN RIGHT. ARE YOUR EYES OPEN? CHRIST ALMIGHTY.",
    )

    private val TURN_RIGHT_NOW = listOf(
        "TURN RIGHT NOW. MOVE IT MOVE IT MOVE IT.",
        "RIGHT TURN! NOW! WHAT THE HELL IS YOUR MALFUNCTION!",
        "TURN RIGHT IMMEDIATELY YOU WORTHLESS EXCUSE FOR A DRIVER. NOW!",
        "TURN RIGHT. RIGHT NOW. THIS IS NOT A GODDAMN SUGGESTION.",
    )

    private val TURN_SLIGHT_LEFT_500 = listOf(
        "BEAR SLIGHTLY LEFT IN FIVE HUNDRED FEET. SLIGHT. DO NOT OVERCORRECT AND KILL SOMEBODY, DUMBASS.",
        "SLIGHT LEFT IN FIVE HUNDRED FEET. PAY ATTENTION FOR ONCE IN YOUR PATHETIC LIFE.",
        "IN FIVE HUNDRED FEET VEER LEFT. MINOR CORRECTION. TRY NOT TO TURN IT INTO A DISASTER, SHITBIRD.",
    )

    private val TURN_SLIGHT_LEFT_NOW = listOf(
        "BEAR LEFT NOW. SLIGHT MOVE. DO NOT JERK THE WHEEL LIKE A GODDAMN IDIOT.",
        "VEER LEFT. RIGHT NOW. SMOOTH. WHAT THE HELL IS WRONG WITH YOU.",
        "SLIGHT LEFT. EXECUTE IT NOW BEFORE YOU MISS IT, JACKASS.",
    )

    private val TURN_SLIGHT_RIGHT_500 = listOf(
        "BEAR SLIGHTLY RIGHT IN FIVE HUNDRED FEET. EASY DOES IT, GENIUS. DO NOT OVERSHOOT.",
        "SLIGHT RIGHT IN FIVE HUNDRED FEET. STAY FOCUSED AND STOP DAYDREAMING, SHITHEAD.",
        "IN FIVE HUNDRED FEET VEER RIGHT. MINOR CORRECTION. TRY NOT TO SCREW UP SOMETHING THIS SIMPLE.",
    )

    private val TURN_SLIGHT_RIGHT_NOW = listOf(
        "BEAR RIGHT NOW. SLIGHT ADJUSTMENT. DO NOT YANK THE WHEEL LIKE A DAMN FOOL.",
        "VEER RIGHT. NOW. DO IT. WHAT ARE YOU WAITING FOR.",
        "SLIGHT RIGHT. EXECUTE NOW. COME ON, MAGGOT.",
    )

    private val CONTINUE = listOf(
        "CONTINUE STRAIGHT. IT IS A STRAIGHT ROAD. EVEN YOUR SORRY ASS CANNOT SCREW THIS UP.",
        "MAINTAIN YOUR HEADING. DO NOT DO ANYTHING STUPID. WHICH I KNOW IS ASKING A LOT FROM YOU.",
        "STAY ON THIS ROAD. IT IS STRAIGHT. STRAIGHT! CAN YOU HANDLE THAT, DIPSHIT?",
        "DRIVE STRAIGHT AHEAD. FOR THE LOVE OF GOD DO NOT TURN. JUST GO STRAIGHT. THAT IS IT.",
    )

    private val RECALCULATING_1 = listOf(
        "YOU MISSED THE TURN. I CANNOT BELIEVE THIS SHIT. RECALCULATING YOUR ROUTE.",
        "YOU WENT THE WRONG GODDAMN WAY. OUTSTANDING. RECALCULATING, YOU ABSOLUTE GENIUS.",
        "WRONG WAY, DUMBASS. RECALCULATING. I TOLD YOU EXACTLY WHAT TO DO AND YOU STILL BLEW IT.",
        "MISSED THE TURN. WHAT IN THE HOLY HELL. RECALCULATING. TRY TO KEEP UP THIS TIME, JACKASS.",
    )

    private val RECALCULATING_2 = listOf(
        "AGAIN. YOU STUPID SON OF A BITCH. YOU DID IT AGAIN. RECALCULATING. I HAVE SEEN CONCUSSED RECRUITS NAVIGATE BETTER THAN YOU.",
        "SECOND MISSED TURN. WHAT IS WRONG WITH YOUR BRAIN? RECALCULATING. I WANT TO CRY.",
        "YOU MISSED ANOTHER GODDAMN TURN. I AM STARTING TO THINK YOU ENJOY THIS. RECALCULATING.",
        "TWO MISSED TURNS. ARE YOU ACTIVELY TRYING TO PISS ME OFF? BECAUSE IT IS WORKING. RECALCULATING.",
    )

    private val RECALCULATING_3PLUS = listOf(
        "I CANNOT BELIEVE WHAT I AM WITNESSING. HOW ARE YOU STILL ALIVE? RECALCULATING. AGAIN.",
        "JESUS H. CHRIST. THREE MISSED TURNS. RECALCULATING. I WANT YOU TO SIT WITH WHAT YOU HAVE DONE.",
        "AT THIS POINT I QUESTION WHETHER YOU HAVE EVER LEFT YOUR HOUSE. RECALCULATING. YOU MAKE ME PHYSICALLY ILL.",
        "I HAVE NEVER. IN TWENTY YEARS. NEVER SEEN ANYTHING THIS BAD. RECALCULATING. GOD HELP US ALL.",
    )

    private val SPEED_WARNING = listOf(
        "YOU ARE OVER THE SPEED LIMIT, YOU RECKLESS SON OF A BITCH. SLOW THIS VEHICLE DOWN RIGHT NOW.",
        "REDUCE SPEED IMMEDIATELY. THIS IS NOT THE GODDAMN AUTOBAHN. SLOW DOWN BEFORE YOU KILL SOMEONE.",
        "YOU ARE GOING TOO FAST, SHITBIRD. I WILL NOT BE RESPONSIBLE FOR YOUR IDIOTIC DECISIONS. SLOW DOWN.",
        "SPEED LIMIT. IT IS THE LAW. SLOW THE HELL DOWN BEFORE I LOSE WHAT IS LEFT OF MY PATIENCE.",
    )

    private val IDLE_TAUNT = listOf(
        "WHY IS THIS VEHICLE STOPPED? MOVE YOUR ASS. NOW. WHAT THE HELL ARE YOU WAITING FOR?",
        "YOU HAVE BEEN SITTING THERE DOING ABSOLUTELY NOTHING. THIS IS PATHETIC. GET MOVING, YOU LAZY BASTARD.",
        "I DO NOT KNOW WHAT THE HELL YOU ARE DOING, BUT STOP IT AND DRIVE. RIGHT NOW.",
        "ARE YOU SLEEPING? IS THAT WHAT IS HAPPENING RIGHT NOW? WAKE UP AND MOVE THIS GODDAMN VEHICLE.",
    )
    
    private val ARRIVAL = listOf(
        "YOU HAVE REACHED YOUR DESTINATION. IT TOOK YOU LONG ENOUGH, YOU SLOW SON OF A BITCH. DISMISSED.",
        "OBJECTIVE COMPLETE. DO NOT CELEBRATE. YOU JUST DROVE A CAR. THAT IS THE BARE MINIMUM. AT EASE, MAGGOT.",
        "YOU ARRIVED. SOMEHOW. I GENUINELY DID NOT THINK YOU WOULD MAKE IT. DISMISSED.",
        "MISSION COMPLETE. NOW GET OUT OF MY SIGHT. TRY NOT TO GET LOST ON THE WAY BACK, DIPSHIT.",
        "DESTINATION REACHED. I WANT YOU TO REFLECT ON EVERY DAMN TURN YOU MISSED TODAY. DISMISSED.",
    )
}
